### ISSUE TITLE
Don't use temporary files for storing secrets

### ISSUE THREAD

**Issue by Maryse47** [mjec/fido2-hmac-secret#1]
**Is your feature request related to a problem? Please describe.**
Using temporary files to store secrets is not secure in general. One example [from wiki](https://github.com/mjec/fido2-hmac-secret/wiki/Arch-Linux-LUKS-configuration):

> Run fido2-hmac-secret generate -f /tmp/0-primary-authenticator.keyslot-0 > /tmp/keyfile to generate some secret data. I'm assuming your /tmp/ is encrypted.

On 99% systems /tmp is on tmpfs (which is systemd default) and tmpfs filesystems aren't encrypted and their contents freely available when machine is running or suspended. This is false assumption.

**Describe the solution you'd like**
Please use unix pipes for passing secrets between tools.

**Describe alternatives you've considered**
I'm not aware of any other secure alternative for passing secrets between different tools.

**Comment by mjec** [comment]
Hi @Maryse47, thanks for raising this issue!

I've taken a look through the source code and this wiki entry, and the corresponding help for the mkinitcpio hook, are the only places that use `/tmp`.

I share your concern about the readability of `/tmp` in general, but the fix isn't trivial. In looking at this, I found that:

 * `cryptsetup` won't accept new key material on stdin if you're unlocking it with a passphrase (as it expects the existing passphrase on stdin); and
 * doing process substitution i.e. `cryptsetup -v luksAddKey /dev/your-encrypted-device <(fido2-hmac-secret generate -f /boot/keyfiles/keyfile)` has a similar issue: `fido2-hmac-secret` can't grab the tty, so you can't enter an encrypted keyfile passphrase.

I think what I'd like to do is permit `fido2-hmac-secret` to take the passphrase in an environment variable, and then instruct folks to do something like this:

```sh
set +e ; read -rs FIDO2_HMAC_SECRET_PASSPHRASE \
  && sudo cryptsetup -v luksAddKey /dev/your-encrypted-device \
       <(fido2-hmac-secret -f /path/to/encrypted/keyfile) \
  ; unset FIDO2_HMAC_SECRET_PASSPHRASE
```

I don't _love_ putting the passphrase in an environment variable, but I believe that's never readable by any other application, and only root should be able to read it out of `/proc`.

What do you think about that approach? If it seems ok to you, I can code it up this weekend.

**Comment by Maryse47** [comment]
Thx for the reply. 

> I've taken a look through the source code and this wiki entry, and the corresponding help for the mkinitcpio hook, are the only places that use /tmp.

It's not only about files in `/tmp` but storing secrets in temporary files in general. You do this in initramfs during unlock: https://github.com/mjec/fido2-hmac-secret/blob/v0.3.0/scripts/initcpio-run.m4#L82

> I don't love putting the passphrase in an environment variable, but I believe that's never readable by any other application, and only root should be able to read it out of /proc.

Initial environment variables for process can be easily dumped with `ps eww aux` by all users unless something like `hidepid` is in use. This doesn't affect temporary variables (not exported) used in script though so those should be safe (unless someone does full memory scan but this is rather out of scope). Maybe you can try something like this:

```
read -rs FIDO2_HMAC_SECRET_PASSPHRASE
LUKS_PASSPHRASE=printf '%s\n' "$FIDO2_HMAC_SECRET_PASSPHRASE" | fido2-hmac-secret -f /path/to/encrypted/keyfile
printf '%s\n' "$LUKS_PASSPHRASE" | sudo cryptsetup -v luksAddKey /dev/your-encrypted-device
```

See also this post: https://lists.gnu.org/archive/html/bug-bash/2019-03/msg00075.html

**Comment by mjec** [comment]
> It's not only about files in /tmp but storing secrets in temporary files in general. You do this in initramfs during unlock

I think this is hard to avoid, because of the way the `encrypt` hook works. We can't pass input directly to it. I'm also not so concerned about it here: initramfs is a single-user root-only ram-only file system, with no suspend support. It becomes inaccessible as soon as control is passed to init; to get back at it from the booted system you need at least the same privileges as required to read disk encryption keys out of memory.

While it is _possible_ for swap to be written out from initramfs, it's pretty unlikely given the size of it (normally tens of MB) compared to the size of modern system RAM. It's possible to avoid it completely by adding `rootfstype=ramfs` as a kernel parameter (per [this doc](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/Documentation/filesystems/ramfs-rootfs-initramfs.txt?id=HEAD)).

Temporary files are also used by other 2FA encryption systems listed in [the Arch wiki](https://wiki.archlinux.org/index.php/Dm-crypt/Specialties#Using_GPG,_LUKS,_or_OpenSSL_Encrypted_Keyfiles), but is there a particular risk in the initramfs context that I'm missing?

Having said all of that, mostly to explain my thinking before now, I suspect there's a good approach we can use that alleviates this concern:

1. create a small loopback file system in a file on initramfs
2. encrypt that with LUKS using a transient passphrase and open it
3. place the decrypted keyfile there
4. during cleanup (after `encrpyt` has finished), close, unmount and delete the device

This adds quite a bit of complexity, but guarantees that key material is never written unencrypted to a device that could be swapped out (because the backing for the loopback mount is encrypted before being written to the initramfs). I'll have to do some experimentation to make sure this is feasible. The biggest downside is it constrains where `cryptkey` can live, but I expect that's fine (I suspect we can `export` a new value here; but again this is something I'll need to test).

If this assuages your concerns, I'll file an issue for it. Not sure I'll get to it this weekend, but will try to work on it before too long.

> Maybe you can try something like this: <snip>

I like this idea! I'll make one small change -- explicitly passing `-` as a final positional argument to cryptsetup, so it has keyfile semantics reading on stdin -- and then package this into a script. I probably won't get to this until tomorrow, so if you're keen feel free to submit a PR.

If you don't get to it before then I'll credit you in CONTRIBUTORS.md and the commit message (unless you let me know I shouldn't).

Thanks for your interest @Maryse47, and for teaching me several things! [This link](https://lists.gnu.org/archive/html/bug-bash/2019-03/msg00075.html) in particular was super informative.

**Comment by Maryse47** [comment]
> I think this is hard to avoid, because of the way the encrypt hook works. We can't pass input directly to it.

Ok, I forgot you need to use `encrypt` hook after decryption. It's possible to move `encrypt` hook functionality to your own however I understand if you think that would be too much for this project. If that's the case then I'm ok with leaving current state for initramfs handling.

I don't think this poses significant risk in practice, I just don't like leaving unsolved problems even when they're mostly theoretical :smile: 

> Temporary files are also used by other 2FA encryption systems listed in the Arch wiki, but is there a particular risk in the initramfs context that I'm missing?

Yes, this is a common problem however there are [existing solutions that doesn't need any temporary files](https://github.com/agherzan/yubikey-full-disk-encryption) (they reimplement encrypt hook themselves).

> I like this idea! I'll make one small change -- explicitly passing - as a final positional argument to cryptsetup, so it has keyfile semantics reading on stdin -- and then package this into a script. I probably won't get to this until tomorrow, so if you're keen feel free to submit a PR.

I can't test anything myself right now so I leave figuring out the details for you :smile:

**Comment by mjec** [comment]
> While it is possible for swap to be written out from initramfs, it's pretty unlikely given the size of it (normally tens of MB) compared to the size of modern system RAM. It's possible to avoid it completely by adding rootfstype=ramfs as a kernel parameter (per this doc).

So for the sake of posterity let me say: I tried setting `rootfstype=ramfs` and broke everything, so probably don't do that ;)

(By broke everything I mean it caused /sbin/init to be not found, which caused a mild panic until I remembered I made that change. I restarted with my fallback bootloader entry, and then removed that kernel parameter.)

**Comment by Maryse47** [comment]
You may update instructions to use https://github.com/mjec/fido2-hmac-secret/commit/22c271a008153e3891878c819b3d8757ae2965ba in
https://github.com/mjec/fido2-hmac-secret/blob/v0.3.0/scripts/initcpio-install.m4#L39
https://github.com/mjec/fido2-hmac-secret/wiki/Arch-Linux-LUKS-configuration

You may also add note that preserving encrypted keyfile is critical and it's important to backup it alongside luks header

**Comment by mjec** [comment]
> You may update instructions to use 22c271a in...

Yup I have a patch coming with this, and changes to initcpio-run.m4 as well. I'll close out this issue and tag 0.4.0 when that's on master.

> You may also add note that preserving encrypted keyfile is critical and it's important to backup it alongside luks header

This is a great suggestion, thanks!
