### ISSUE TITLE
FIDO_ERR_PIN_REQUIRED on enroll

### ISSUE THREAD

**Issue by linuxgemini** [mjec/fido2-hmac-secret#28]
**Describe the bug**
While enrolling a FIDO2 device with PIN being set, khefin exits with the FIDO2 error `FIDO_ERR_PIN_REQUIRED`

**To Reproduce**
1. (If not done already) Set a PIN to your FIDO2 key.
2. `khefin enrol -d <hidraw address of the FIDO2 key> -f /tmp/0-primary-authenticator`
3. See error `khefin: Unable to create credential on FIDO2 device: FIDO_ERR_PIN_REQUIRED (0x36)`

**Expected behavior**
Successful enrollment.

**Environment:**
 - Operating system: _Arch Linux_
 - Version: _0.5.0_
 - Authenticator make and model: _Yubikey 5 NFC and Solo Tap_

**Additional context**
It seems like khefin doesn't support FIDO2 keys with PINs, this should be documented further.

**Comment by mjec** [comment]
Hi @linuxgemini, thanks for the report! You're right we're missing PIN support.

I think to make this happen we need to prompt for the PIN, and to pass it into `fido_dev_make_cred` here: https://github.com/mjec/khefin/blob/913ce0c70f6d6a268a555ab4514e9d469f8a944c/src/authenticator.c#L295-L296 and `fido_dev_get_assert` here: https://github.com/mjec/khefin/blob/913ce0c70f6d6a268a555ab4514e9d469f8a944c/src/authenticator.c#L405-L406

I think it'd be good to keep `create_credential` and `get_secret_from_authenticator_params` non-interactive, so we probably need to add the pin string to `authenticator_parameters_t` (or as a new parameter to those functions). We can check `fido_dev_has_pin` and PIN length in those functions too, to make sure we have it if required.

If anyone reading wants to pick this up feel free to take it on (just leave a comment to avoid duplicating work), otherwise I'll take a pass at this sometime in the next week or so.
