### ISSUE TITLE
Why binary needs to be setuid?

### ISSUE THREAD

**Issue by Maryse47** [mjec/fido2-hmac-secret#3]
As [README](https://github.com/mjec/fido2-hmac-secret/tree/v0.3.0#installation) says:

> Note that make install requires root privileges, because the binary should run as setuid root.

Generally any setuid root binary in system is a red flag and historically most if not all such binaries were used for malicious full priv escalation and had to be fixed (perhaps someone could accept challenge for exploiting this app :smile:).

While looking at the purpose of this app I don't understand why it needs to be setuid and I recommend not making it setuid by default unless it's absolutely needed  (but I don't believe so). Any privilege escalation can be done through sudo when needed.

**Comment by Maryse47** [comment]
Is it because it needs to read encrypted keyfile? In such case using `sudo` should be enough on running system and in initramfs it's called by root anyway.

**Comment by mjec** [comment]
root is required to issue `mlockall`, disable core dumps and increase memlock rlimit (which is required to lock future memory). This is necessary to avoid the possibility of secrets being swapped out. The first thing we do is set these and drop privileges; see https://github.com/mjec/fido2-hmac-secret/blob/master/src/memory.c (first line of `main()` is `lock_memory_and_drop_privileges()`).

I did look at using a less invasive locking mechanism - like [libsodium's `sodium_mlock`](https://download.libsodium.org/doc/memory_management), but the underlying libraries (libcbor and libfido2) don't have the same protections, and do handle sensitive data. It is possible to compile libcbor with custom malloc (etc) implementations, but writing a thread-safe secure memory allocator is beyond the scope of this project ;).

In fact you _can_ run this without setuid root; by default it will spew some warnings, but these can be silenced by setting the `FIDO2_HMAC_SECRET_SILENCE_MEMLOCK_ERRORS` environment variable (or by making with `-DALWAYS_SILENCE_MEMORY_LOCK_ERRORS=1`). This is explained in the `NOTES` section of the man page, but I will add something to the readme to clarify.

If you have other ideas for how to achieve similar memory locking without root, I'd love to hear them.

**Comment by Maryse47** [comment]
Ok, but why you just don't raise privileges trough sudo instead? Honestly I think running as setuid is bigger risk than potentially swapping some secrets. There are many encryption related tools like `openssl` or `gpg` and they don't need to run as setuid. It will be better to make setuid build as opt-in instead of opt-out.

**Comment by mjec** [comment]
> There are many encryption related tools like `openssl` or `gpg` and they don't need to run as setuid.

Yeah, but both of those use their own memory allocators to mitigate the risk of memory being swapped out.

> Ok, but why you just don't raise privileges trough sudo instead?

I think this is dramatically _more_ dangerous -- once running with sudo, we can't drop privileges[1], and so more code is running as root, which to my mind creates a higher risk of bad code running as root.

Having said that, I recognize that setuid is an uncommon thing for small applications to require. Doing ` find / -perm -u+s -uid 0 -type f` I found only a handful of apps requiring it: some coreutils, virtualbox, ssh-keysign, polkit, and for some reason electron apps' version of chrome-sandbox.

My initial thought was to make setuid opt-in instead of opt-out, but I did some research and I think there's an even better solution: setcap. Running `sudo setcap cap_ipc_lock+ep /path/to/fido2-hmac-secret` has the same effect, and without requiring root permissions ever. I'm going to add that to the `Makefile`, and remove the uid == 0 warnings. Does this sound like the right move to you?

[1] because `getuid()` still returns `0`, you have to have a configuration option for what user to drop to; and `nobody` is a poor choice because we need access to /dev/hidraw*.

**Comment by Maryse47** [comment]
> [1] because getuid() still returns 0, you have to have a configuration option for what user to drop to; and nobody is a poor choice because we need access to /dev/hidraw*.

From what I read briefly, [it's possible to go back to invoking user with sudo](https://unix.stackexchange.com/questions/353206/is-there-a-reverse-sudo/353209#353209).

> Having said that, I recognize that setuid is an uncommon thing for small applications to require. Doing find / -perm -u+s -uid 0 -type f I found only a handful of apps requiring it: some coreutils, virtualbox, ssh-keysign, polkit, and for some reason electron apps' version of chrome-sandbox.

Yes, many distros like fedora, ubuntu (for main), opensuse are reluctant to add applications that need setuid in their repos so this would make popularizing your implementation difficult.

> Running sudo setcap cap_ipc_lock+ep /path/to/fido2-hmac-secret has the same effect, and without requiring root permissions ever. I'm going to add that to the Makefile, and remove the uid == 0 warnings. Does this sound like the right move to you?

Yeah, single capability instead of full setuid is a way better however reading [manpage](https://linux.die.net/man/2/mlockall):

> Since Linux 2.6.9, no limits are placed on the amount of memory that a privileged process can lock and **the RLIMIT_MEMLOCK soft resource limit instead defines a limit on how much memory an unprivileged process may lock.** 

On my system:
```
RESOURCE   DESCRIPTION                              SOFT       HARD UNITS
MEMLOCK    max locked-in-memory address space 1073741824 1073741824 bytes
```
which sounds enough. Maybe tweaking memlock rlimit isn't needed at all then?

**Comment by Maryse47** [comment]
After looking closer it seems that memlock default is just 64kb which indeed may be too small. So I reccomend in order of preference:
1. Use sudo if not running as root, do the job and return to invoking user to continue operations.
2. Add cap_ipc_lock to installed binary.

**Comment by mjec** [comment]
> From what I read briefly, it's possible to go back to invoking user with sudo.

TIL. I was sure there had to be a way, but I hadn't investigated deeply.

> After looking closer it seems that memlock default is just 64kb which indeed may be too small.

Yeah that's the limit on my machine, which is how I got into this rabbit hole ;)

> in order of preference:

To me the main question is whether we should default to `setcap` or not. I've got a patch so toggling it is a matter of `make install SETCAP_BINARY=0` (or `=1`).

My impression is that setting a capability is better than running under sudo (or asking folks to do so), precisely because it's more limited. If we're asking folks to run under sudo to avoid a warning, that's pretty close to setuid (but with a user step). As such my instinct says we should setcap by default, make it clear in the README, and make it easy to opt out.

To that end I'd update readme to relevantly include:

## Installation

### Dependencies

Before building or running this tool, you'll need the following dependencies installed:

 * [libfido2](https://developers.yubico.com/libfido2/)
 * [libcbor](https://libcbor.readthedocs.io/en/v0.5.0/) - also a dependency of libfido2
 * [libsodium](https://download.libsodium.org/doc/)

At the moment I believe this tool is linux-only; issue reports or pull requests to improve portability are gratefully accepted.

### Building

`make release` is the main compile target.

If you want a [bash-completion](https://github.com/scop/bash-completion) script, add the `bash-completions` target; and if you want `mkinitcpio` hooks add the `initcpio` target. To compile with all, run `make release bash-completions initcpio`.

You can set the maximum passphrase length (defaults to 1024; everything after this will be ignored) by appending `LONGEST_VALID_PASSPHRASE=<some integer>` after the list of targets.

You disable memory locking warnings (default to on) by setting `WARN_ON_MEMORY_LOCK_ERRORS=0` (see the memeory locking section below).

### Installing

`make install` is the main installation target. That will install bash completions and `mkinitcpio` hooks if they were compiled.

The `DESTDIR` and `PREFIX` variables are respected (so you can do `sudo make install PREFIX=/usr`, for example, to install to `/usr/bin` instead of `/usr/local/bin`).

By default `make install` will give the installed binary `CAP_IPC_LOCK` capabilities (see the memory locking section below). You can skip this by running `make install SETCAP_BINARY=0` instead.

## Memory locking

To avoid secrets accidentally being written to disk (including swap space), the binary will disable core dumps and lock all allocated memory. The success of this depends on your locally-configured limits (and in particular `RLIMIT_MEMLOCK`) and the capabilities of the binary. To ensure success, by default the binary is given the `CAP_IPC_LOCK` capability during `make install` (see above). This bypasses `RLIMIT_MEMLOCK`.

If for any reason core dumps cannot be disabled or memory cannot be locked, a warning will be generated, unless the binary was compiled with `WARN_ON_MEMORY_LOCK_ERRORS=0`.

**Comment by mjec** [comment]
Oh also @Maryse47 for adding you to CONTRIBUTORS.md, at the moment I've got:

* [Maryse47](https://github.com/Maryse47) - security suggestions and contributions

Are you happy with that?

**Comment by Maryse47** [comment]
> My impression is that setting a capability is better than running under sudo (or asking folks to do so), precisely because it's more limited. If we're asking folks to run under sudo to avoid a warning, that's pretty close to setuid (but with a user step).

That user step (authentication) is crucial difference to setuid which doesn't have any authentication. Personally I would be more comfortable with running `fido2-hmac-secret` as root through `sudo` all the way like `sudo fido2-hmac-secret generate -f /tmp/0-primary-authenticator.keyslot-0 > /boot/keyfiles/xxx` rather than moving files from `/tmp` manually in separate step.

 Using `CAP_IPC_LOCK` is acceptable though if this is what you prefer. Note that you need `libcap` dependency to add capabilities during install.

> Are you happy with that?

Ok
