### ISSUE TITLE
Question - Sensitivity of encrypted keyfiles

### ISSUE THREAD

**Issue by Algebro7** [mjec/fido2-hmac-secret#38]
Hello,

I'm setting up khefin for 2FA for LUKS but I want to make sure I understand the security implications of storing the keyfiles generated by `khefin enrol` in an unencrypted /boot partition. Is it possible to unlock the LUKS device without the yubikey if an attacker has access to that file? The docs mention the file should be owned by root and have permissions set to `400`, but boot partitions are often FAT32 and don't support permissions. 

It may sound dumb but based on my understanding, [some other implementations](https://github.com/agherzan/yubikey-full-disk-encryption) appear to only use the yubikey to generate a static password once and then use that as the LUKS passphrase, so it becomes more of a very strong 1fa than a true 2fa. I'm guessing there might be no way around that without patching LUKS to support a dynamically generated passphrase via U2F?

Thanks!

**Comment by mjec** [comment]
Hi @Algebro7!

The encrypted key file is never enough to open the drive, even if the passphrase for that key file is known. The decrypted key file contains some static data, which the Yubikey converts into the disk encryption key.

That said, your disk encryption key will always be a single static secret. It's not really possible to have dynamically keyed encryption. The closest I can think of is a hardware security module (HSM), which still has a static key, just stored within a tamper-proof hardware module. These devices are state of the art, but very expensive (think 20x the cost of a Yubikey).

So you're right in some ways that this is "very strong 1FA". However, this package (and from my brief reading, yubikey-full-disk-encryption) doesn't ever store the key in one place, so deriving the key requires two factors: your Yubikey, and your decrypted key file.

The whole idea of "authentication factors" (from which we get the idea of 2FA) is specific to authentication, rather than encryption, which I think causes some of the confusion here. Encryption is a very different process to authentication, and I don't know of any form of encryption that doesn't in the end depend on a single, static key.

**Comment by Algebro7** [comment]
Thanks a lot for the detailed response! That explanation makes sense. One quick thing I'm a little unclear about:

> That said, your disk encryption key will always be a single static secret. It's not really possible to have dynamically keyed encryption.

cryptsetup allows swapping/changing of secrets in keyslots to unlock the drive. I'm guessing this works by encrypting a symmetric key with the slot's passphrase that is used to perform the decryption and storing it in the header, is that correct? If so, that makes sense to me why you wouldn't be able to modify a keyslot at decryption time.

Closing, and thanks again!

**Comment by mjec** [comment]
Yup you've got it right!

In its usual operation, the LUKS header contains a single master symmetric key which is actually used for encrypting and decrypting your data. That master key is then encrypted using a symmetric key derived from your passphrase, and that encrypted key is what's stored in the key slot (together with some metadata). (This process of having a master key means you can change your passphrase without re-encrypting your hard disk, and you can have multiple passphrases to unlock the disk.)

Every 2FA system I'm aware of for disk encryption, including the FIDO2 support in LUKS2 from systemd v248, is essentially generating the passphrase in that process.
